/* Copyright 2014 URL IS/IT
 * Licensed under the Apache License, Version 2.0 (the "License"); you  may  not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless  required  by  applicable  law  or  agreed  to  in  writing,  software
 * distributed under the License is distributed on an  "AS  IS"  BASIS,  WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either  express  or  implied.  See  the
 * License for the specific language governing permissions and limitations under
 * the License. */
package com.urlisit.siteswrapper.cloud.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.google.appengine.api.datastore.Key;

/**
 * Contains the document Id of the Google Apps Script spreadsheet used to
 * initialize the data-store.
 *
 * @author Todd Url
 */
@Entity
public class DocumentId {

  /*
   * Autogenerated primary key
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Key key;
  
  /*
   * The document Id
   */
  private String id;
  
  /**
   * Returns the document id of the Google Apps Script spreadsheet used to
   * initialize the data-store.
   * 
   * @return The document id
   */
  public String getId() {
    return id;
  }
  
  /**
   * Stores the value of the document id of the Google Apps Script spreadsheet
   * used to initialize the data-store.
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }
  
  /**
   * Returns the key used by the data-store to uniquely identify this object.
   * 
   * @return The key unique to an instance of this class
   */
  public Key getKey() {
    return key;
  }

}